server:
  servlet:
    application-display-name: wlw-sys-web
  port: 8011
  tomcat:
    uri-encoding: UTF-8
wlw-sys-web:
  rest:
    username: guest
    password: guest
endpoints:
  shutdown:
    security:
      user:
        name: guest
        password: guest
spring:
  application:
    name: wlw-sys-web
  profiles:
    active: dev
  http:
    encoding:
  messages:
    encoding: UTF-8
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: true
  client:
    config:
      default:
        loggerLevel: full
