server:
  port: 8010

spring:
  datasource:
    url: jdbc:mysql://rm-bp1t93tie621nh88odo.mysql.rds.aliyuncs.com:3306/wlw?useUnicode=yes&characterEncoding=utf-8&useSSL=no&serverTimezone=Asia/Shanghai
    username: wlw
    password: wlw
  influx:
    url: http://118.31.189.96:8087
    user: jike123
    password: jk123
    database: Test
  mqtt:
    username: admin                            # 账号
    password: public                        # 密码
    host-url: tcp://118.31.189.96:11883    # mqtt连接tcp地址
    client-id: mq-dky-0813        # 客户端Id，每个启动的id要不同
    default-topic: t/#       # 默认主题
    timeout: 100                            # 超时时间
    keepalive: 100

# REDIS
redis:
  address: r-bp19caa71c7ac8f4pd.redis.rds.aliyuncs.com:6379
  host: r-bp19caa71c7ac8f4pd.redis.rds.aliyuncs.com
  port: 6379
  password: Redis352674802
  maxIdle: 10
  maxTotal: 100
  maxWaitMillis: 1000

ali:
  iot:
    accessKey: LTAIZOpGhq6KtGqU
    accessSecret: xi2neJPmjJqDOmtjzTL9pBq8yLXogZ
    clientId: 123
    instanceId:
    consumerGroupId: jmz9pAJ1HzawVqA2N3r9000100
    productKeys: a1dg6xBsM9h
    regionId: cn-shanghai
    deviceTemplate:
    productCode: Iot
    domain: iot.cn-shanghai.aliyuncs.com

# RabbitMQ配置
amqp:
  prefix: dev
  host: 47.112.154.205
  username: dev
  password: 123456
  port: 5672

initialization:
  name: 超级管理员
  mobile:
  loginId: admin
  password: 123456